Repository aiidateam/aiida-core, pull requests merged in 2018-08, with the labels that each got.

#1861 Adding UUID support to hashing
  aiida/backends/tests/generic.py
  aiida/backends/tests/nodes.py
  aiida/common/hashing.py
Labels: topic/HashingAndDuplicates

#1856 Fix plugin fixture setup profile
  .ci/test_fixtures.py
  .ci/test_plugin_testcase.py
  aiida/utils/fixtures.py
Labels: type/bug

#1764 Support current link types/link rules (support for workchains and workflows) at the import/export
  aiida/backends/tests/export_and_import.py
  aiida/cmdline/commands/exportfile.py
  aiida/cmdline/commands/importfile.py
  aiida/cmdline/commands/rehash.py
  aiida/common/archive.py
  aiida/orm/importexport.py
  aiida/tools/dbexporters/tcod.py
Labels: topic/Sharing, topic/Workflows
