Repository aiidateam/aiida-core, pull requests merged in 2018-07, with the labels that each got.

#1661 Converted verdi user to click yo
  .ci/setup_profiles.sh
  .ci/test_setup.py
  .pre-commit-config.yaml
  aiida/backends/tests/__init__.py
  aiida/backends/tests/cmdline/commands/test_user.py
  aiida/backends/tests/verdi_commands.py
  aiida/cmdline/commands/user.py
  aiida/cmdline/params/arguments/__init__.py
  aiida/cmdline/params/arguments/overridable.py
  aiida/cmdline/params/options/__init__.py
  aiida/cmdline/params/options/conditional.py
  aiida/cmdline/params/options/interactive.py
  aiida/cmdline/params/options/multivalue.py
  aiida/cmdline/params/options/overridable.py
  aiida/cmdline/params/options/test_conditional.py
  aiida/cmdline/params/options/test_interactive.py
  aiida/cmdline/params/types/__init__.py
  aiida/cmdline/params/types/calculation.py
  aiida/cmdline/params/types/choice.py
  aiida/cmdline/params/types/code.py
  aiida/cmdline/params/types/computer.py
  aiida/cmdline/params/types/data.py
  aiida/cmdline/params/types/group.py
  aiida/cmdline/params/types/identifier.py
  aiida/cmdline/params/types/multiple.py
  aiida/cmdline/params/types/node.py
  aiida/cmdline/params/types/nonemptystring.py
  aiida/cmdline/params/types/plugin.py
  aiida/cmdline/params/types/shebang.py
  aiida/cmdline/params/types/user.py
  aiida/cmdline/verdilib.py
  aiida/control/postgres.py
  aiida/orm/implementation/django/user.py
  aiida/orm/implementation/sqlalchemy/user.py
  aiida/orm/user.py
  aiida/transport/__init__.py
  aiida/transport/plugins/local.py
  aiida/transport/plugins/ssh.py
  docs/source/nitpick-exceptions
Labels: topic/VerdiCommandLine, type/accepted feature

#1701 Migrate verdi group command to use click
  .pre-commit-config.yaml
  aiida/backends/tests/__init__.py
  aiida/backends/tests/cmdline/commands/test_group.py
  aiida/cmdline/commands/group.py
Labels: topic/VerdiCommandLine

#1724 skip pgtest related testcases until #1722 is fixed
  .ci/test_fixtures.py
  .ci/test_plugin_testcase.py
  .ci/test_setup.py
  aiida/control/tests/test_postgres.py
Labels: priority/critical-blocking, topic/TestInfrastructure

#1725 skip pgtest related testcases in branch verdi until #1722 is fixed
  .ci/test_fixtures.py
  .ci/test_plugin_testcase.py
  .ci/test_setup.py
  aiida/control/tests/test_postgres.py
Labels: priority/critical-blocking, topic/TestInfrastructure

#1705 Do not allow the copy or deepcopy of Node, except for Data
  aiida/backends/tests/calculation_node.py
  aiida/backends/tests/dataclasses.py
  aiida/backends/tests/nodes.py
  aiida/backends/tests/orm/mixins.py
  aiida/backends/tests/work/work_chain.py
  aiida/orm/data/__init__.py
  aiida/orm/implementation/django/node.py
  aiida/orm/implementation/general/node.py
  aiida/orm/implementation/sqlalchemy/node.py
  aiida/orm/mixins.py
  aiida/work/job_processes.py
  aiida/work/processes.py
  docs/source/developer_guide/internals.rst
Labels: priority/critical-blocking, type/bug

#1732 Migrate verdi shell to click
  .pre-commit-config.yaml
  aiida/cmdline/commands/shell.py
  aiida/cmdline/verdilib.py
  setup_requirements.py
Labels: coding-day/wip, topic/VerdiCommandLine, type/accepted feature

#1651 Migrate `verdi profile` to use the click infrastructure (#1591)
  .pre-commit-config.yaml
  aiida/backends/tests/__init__.py
  aiida/backends/tests/cmdline/commands/test_profile.py
  aiida/cmdline/commands/profile.py
Labels: topic/VerdiCommandLine, type/accepted feature

#1738 Move verdi data to click
  .pre-commit-config.yaml
  aiida/backends/tests/__init__.py
  aiida/backends/tests/cmdline/commands/test_data.py
  aiida/backends/tests/verdi_commands.py
  aiida/cmdline/commands/data.py
  aiida/cmdline/commands/data/__init__.py
  aiida/cmdline/commands/data/array.py
  aiida/cmdline/commands/data/bands.py
  aiida/cmdline/commands/data/cif.py
  aiida/cmdline/commands/data/deposit.py
  aiida/cmdline/commands/data/export.py
  aiida/cmdline/commands/data/list.py
  aiida/cmdline/commands/data/parameter.py
  aiida/cmdline/commands/data/remote.py
  aiida/cmdline/commands/data/show.py
  aiida/cmdline/commands/data/structure.py
  aiida/cmdline/commands/data/trajectory.py
  aiida/cmdline/commands/data/upf.py
  aiida/cmdline/commands/devel.py
  aiida/cmdline/params/options/overridable.py
  docs/source/developer_guide/data_cmdline.rst
Labels: coding-day/done, topic/VerdiCommandLine
