Repository aiidateam/aiida-core, pull requests merged in 2018-06, with the labels that each got.

#1668 Migrate (legacy) workflow command to click
  .pre-commit-config.yaml
  aiida/backends/tests/__init__.py
  aiida/backends/tests/cmdline/commands/test_workflow.py
  aiida/backends/tests/cmdline/params/types/test_workflow.py
  aiida/cmdline/commands/__init__.py
  aiida/cmdline/commands/workflow.py
  aiida/cmdline/params/options/__init__.py
  aiida/cmdline/params/types/__init__.py
  aiida/cmdline/params/types/legacy_workflow.py
  aiida/cmdline/templates/deprecated.tpl
  aiida/cmdline/utils/decorators.py
  aiida/orm/implementation/sqlalchemy/workflow.py
  aiida/orm/utils/loaders.py
Labels: coding-day/done, topic/OldWorkflows, topic/VerdiCommandLine, type/accepted feature

#1680 Creating unique constraint & indexes at the db_dbgroup_dbnodes table in SQLA
  aiida/backends/sqlalchemy/migrations/versions/59edaf8a8b79_adding_indexes_and_constraints_to_the_.py
  aiida/backends/sqlalchemy/models/group.py
Labels: topic/SQLAlchemy

#1655 Migrate verdi code
  .pre-commit-config.yaml
  aiida/backends/tests/cmdline/commands/test_code.py
  aiida/backends/tests/verdi_commands.py
  aiida/cmdline/commands/code.py
  aiida/cmdline/params/arguments/__init__.py
  aiida/cmdline/params/options/__init__.py
  aiida/cmdline/params/types/__init__.py
  aiida/cmdline/params/types/path.py
  aiida/orm/implementation/general/code.py
  docs/source/nitpick-exceptions
Labels: topic/VerdiCommandLine, type/accepted feature
