Repository aiidateam/aiida-core, pull requests merged in 2018-02, with the labels that each got.

#1118 Add 'parser_name' to jobprocess _options
  aiida/work/legacy/job_process.py
Labels: priority/critical-blocking, topic/JobCalculationAndProcess, type/bug

#1133 Add support for VESTA to verdi data cif show
  aiida/cmdline/commands/data.py
Labels: priority/nice to have, type/accepted feature

#1136 Fix a bug in store method of CifData
  aiida/orm/data/cif.py
Labels: priority/important

#1137 Docs: how to install RabbitMQ on Gentoo Linux
  docs/source/install/details.rst
  docs/source/install/details/os.rst
Labels: topic/DocumentationAndCodeStructure

#1152 Fix daemon timeout
  aiida/work/rmq.py
  requirements.txt
Labels: priority/critical-blocking, topic/DocumentationAndCodeStructure, topic/Workflows, type/bug

#1151 Add installation instructions for RabbitMQ to the documentation
  docs/source/install/details.rst
  docs/source/install/details/os.rst
  docs/source/install/details/rabbitmq.rst
  docs/source/install/installation.rst
Labels: topic/DocumentationAndCodeStructure, topic/Workflows

#1168 Fix problem with prematurely erased sandbox folder retrieved_temporary_folder
  .travis-data/test_daemon.py
  aiida/daemon/execmanager.py
  aiida/parsers/simpleplugins/templatereplacer/doubler.py
  setup.py
Labels: priority/critical-blocking, topic/Daemon, topic/JobCalculationAndProcess, type/bug

#1111 Restore proper mutability implementation of Node attributes
  aiida/backends/djsite/db/migrations/0008_code_hidden_to_extra.py
  aiida/backends/djsite/db/migrations/__init__.py
  aiida/backends/djsite/db/models.py
  aiida/backends/sqlalchemy/migrations/versions/35d4ee9a1b0e_code_hidden_attr_to_extra.py
  aiida/backends/tests/calculation_node.py
  aiida/backends/tests/nodes.py
  aiida/backends/tests/verdi_commands.py
  aiida/cmdline/commands/code.py
  aiida/orm/data/__init__.py
  aiida/orm/implementation/django/calculation/job/__init__.py
  aiida/orm/implementation/general/calculation/__init__.py
  aiida/orm/implementation/general/calculation/job/__init__.py
  aiida/orm/implementation/general/calculation/work.py
  aiida/orm/implementation/general/code.py
  aiida/orm/implementation/general/computer.py
  aiida/orm/implementation/general/node.py
  aiida/orm/mixins.py
  aiida/orm/test.py
  docs/source/developer_guide/internals.rst
  docs/source/orm/dev.rst
Labels: priority/critical-blocking, topic/ProvenanceConceptsAndLinks, type/bug
