Repository aiidateam/aiida-core, pull requests merged in 2019-02, with the labels that each got.

#2464 Ensure nested `calcfunctions` work as long `store_provenance=False`
  aiida/backends/tests/work/test_calcfunctions.py
  aiida/work/processes.py
Labels: priority/important, topic/ProvenanceConceptsAndLinks, type/bug

#2413 Export/import of comments (#1760)
  aiida/backends/tests/export_and_import.py
  aiida/backends/tests/orm/comments.py
  aiida/cmdline/commands/cmd_export.py
  aiida/orm/__init__.py
  aiida/orm/importexport.py
  aiida/orm/querybuilder.py
  docs/source/import_export/main.rst
  docs/source/querying/querybuilder/usage.rst
Labels: coding-day/done, priority/nice to have, topic/ExportImport

#2416 Export/import of extras:
  aiida/backends/tests/export_and_import.py
  aiida/cmdline/commands/cmd_import.py
  aiida/orm/importexport.py
Labels: coding-day/done, topic/ExportImport, type/accepted feature

#2472 Ex-/import process_type column - Tests for correct export/import of v0.4 export-files
  aiida/backends/tests/export_and_import.py
  aiida/orm/importexport.py
Labels: coding-day/done

#2511 Added node label in the tree end point response
  aiida/backends/tests/restapi.py
  aiida/restapi/translator/node.py
Labels: topic/RestApi

#2545 bug fix for `verdi node delete`
  aiida/cmdline/commands/node.py
Labels: aiida-core 0.x
