Repository aiidateam/aiida-core, pull requests merged in 2020-05, with the labels that each got.

#4044 Docs: add the "Topics - Command line interface" section
  docs/source/topics/cli.rst
  docs/source/verdi/verdi_user_guide.rst
Labels: pr/on-hold

#3599 Import/export progress bar
  aiida/cmdline/commands/cmd_export.py
  aiida/cmdline/commands/cmd_import.py
  aiida/cmdline/commands/cmd_restapi.py
  aiida/cmdline/params/options/__init__.py
  aiida/common/folders.py
  aiida/common/lang.py
  aiida/common/log.py
  aiida/tools/importexport/common/__init__.py
  aiida/tools/importexport/common/archive.py
  aiida/tools/importexport/common/config.py
  aiida/tools/importexport/common/exceptions.py
  aiida/tools/importexport/common/progress_bar.py
  aiida/tools/importexport/common/utils.py
  aiida/tools/importexport/dbexport/__init__.py
  aiida/tools/importexport/dbexport/utils.py
  aiida/tools/importexport/dbimport/__init__.py
  aiida/tools/importexport/dbimport/backends/django/__init__.py
  aiida/tools/importexport/dbimport/backends/sqla/__init__.py
  aiida/tools/importexport/dbimport/utils.py
  docs/requirements_for_rtd.txt
  docs/source/verdi/verdi_user_guide.rst
  environment.yml
  requirements/requirements-py-3.5.txt
  requirements/requirements-py-3.6.txt
  requirements/requirements-py-3.7.txt
  requirements/requirements-py-3.8.txt
  setup.json
  tests/cmdline/commands/test_export.py
  tests/cmdline/commands/test_import.py
  tests/orm/implementation/test_comments.py
  tests/orm/implementation/test_logs.py
  tests/orm/implementation/test_nodes.py
  tests/tools/importexport/orm/test_attributes.py
  tests/tools/importexport/orm/test_calculations.py
  tests/tools/importexport/orm/test_codes.py
  tests/tools/importexport/orm/test_comments.py
  tests/tools/importexport/orm/test_computers.py
  tests/tools/importexport/orm/test_extras.py
  tests/tools/importexport/orm/test_groups.py
  tests/tools/importexport/orm/test_links.py
  tests/tools/importexport/orm/test_logs.py
  tests/tools/importexport/orm/test_users.py
  tests/tools/importexport/test_complex.py
  tests/tools/importexport/test_deprecation.py
  tests/tools/importexport/test_prov_redesign.py
  tests/tools/importexport/test_simple.py
  tests/tools/importexport/test_specific_import.py
Labels: pr/ready-for-review

#4085 Increase the minimal required version of setuptools to 42.0.0 [py35].
  .github/workflows/ci.yml
  .github/workflows/test-install.yml
  setup.py
Labels: topic/dependencies

#4074 Move in place three sections to docs "How-to" (in Managing your installation)
  docs/source/backup/backup-aiidadb-USERNAME
  docs/source/backup/index.rst
  docs/source/backup/pgpass
  docs/source/howto/backup_postgresql.sh
  docs/source/howto/data.rst
  docs/source/howto/installation.rst
  docs/source/howto/installation_more/index.rst
  docs/source/howto/load-singlesshagent.sh
  docs/source/index.rst
  docs/source/install/installation.rst
  docs/source/install/updating_installation.rst
  docs/source/reference/backup_script.rst
  docs/source/working_with_aiida/index.rst
  docs/source/working_with_aiida/tips/for_cluster_admins.rst
  docs/source/working_with_aiida/tips/repo_indexing.rst
  docs/source/working_with_aiida/troubleshooting.rst
Labels: topic/documentation

#4070 Docs: Add first draft for tutorial
  docs/source/_static/custom.css
  docs/source/tutorial/basic.rst
  docs/source/tutorial/include/calcfun_graph.png
  docs/source/tutorial/include/calcjob_graph.png
  docs/source/tutorial/include/workchain_graph.png
Labels: pr/on-hold, topic/documentation

#4087 Docs: Add HowTo on running workflows
  docs/source/howto/workflows.rst
Labels: topic/documentation

#4114 Docs: How to run external codes
  docs/source/howto/codes.rst
  docs/source/howto/installation.rst
Labels: topic/documentation

#4080 Docs: Move in section on QueryBuilder to How-To
  docs/source/howto/data.rst
  docs/source/querying/querybuilder/append.rst
  docs/source/querying/querybuilder/intro.rst
  docs/source/querying/querybuilder/queryhelp.rst
Labels: topic/documentation

#4060 Docs: revamp Intro/Install
  docs/requirements_for_rtd.txt
  docs/source/_static/aiida-custom.css
  docs/source/_static/custom.css
  docs/source/_static/link-box.css
  docs/source/howto/data.rst
  docs/source/index.rst
  docs/source/install/configuration.rst
  docs/source/install/installation.rst
  docs/source/install/prerequisites.rst
  docs/source/install/quick_installation.rst
  docs/source/install/troubleshooting.rst
  docs/source/intro/about.rst
  docs/source/intro/get_started.rst
  docs/source/intro/installation.rst
  docs/source/intro/troubleshooting.rst
  setup.json
Labels: topic/documentation

#4126 Docs: How to organize data - Group path
  docs/source/howto/data.rst
Labels: topic/documentation

#4127 Add brief intro text to "About" page.
  docs/source/index.rst
  docs/source/intro/about.rst
Labels: topic/documentation

#4113 Docs: add "How To - Grouping nodes" section
  docs/source/howto/data.rst
  docs/source/topics/provenance/consistency.rst
  docs/source/working_with_aiida/groups.rst
Labels: topic/documentation

#3966 Docs: add a Frequently Asked Questions page
  README.md
  docs/source/howto/faq.rst
  docs/source/howto/installation.rst
  docs/source/index.rst
  docs/source/intro/troubleshooting.rst
  docs/source/topics/plugins.rst
Labels: pr/ready-for-review

#4112 Docs: Add HowTo on writing workflows
  docs/source/howto/workflows.rst
Labels: topic/documentation

#4093 Docs: How to interface external codes
  docs/source/howto/codes.rst
Labels: topic/documentation

#4132 Docs: Add advanced querying section to database topics
  docs/source/howto/data.rst
  docs/source/topics/database.rst
Labels: topic/documentation

#4131 Docs: Move section about log-level to new troubleshooting page.
  docs/source/howto/faq.rst
  docs/source/intro/troubleshooting.rst
  docs/source/working_with_aiida/troubleshooting.rst
Labels: topic/documentation

#4135 Docs: final touches
  aiida/tools/dbimporters/plugins/icsd.py
  docs/source/conf.py
  docs/source/howto/codes.rst
  docs/source/howto/data.rst
  docs/source/howto/include/backup_postgresql.sh
  docs/source/howto/include/load-singlesshagent.sh
  docs/source/howto/installation.rst
  docs/source/howto/plugins.rst
  docs/source/howto/visualising_graphs/visualising_graphs.rst
  docs/source/intro/about.rst
  docs/source/intro/installation.rst
  docs/source/intro/tutorial.rst
  docs/source/querying/backend.rst
  docs/source/querying/querybuilder/append.rst
  docs/source/querying/querybuilder/intro.rst
  docs/source/querying/querybuilder/queryhelp.rst
  docs/source/topics/calculations/concepts.rst
  docs/source/topics/calculations/usage.rst
  docs/source/topics/plugins.rst
  docs/source/topics/processes/concepts.rst
  docs/source/topics/processes/functions.rst
  docs/source/topics/processes/include/snippets/serialize/run_workchain_serialize.py
  docs/source/topics/processes/include/snippets/serialize/workchain_serialize.py
  docs/source/topics/processes/usage.rst
  docs/source/topics/provenance/consistency.rst
  docs/source/topics/workflows/concepts.rst
  docs/source/topics/workflows/usage.rst
  docs/source/verdi/verdi_user_guide.rst
Labels: topic/documentation
