Repository aiidateam/aiida-core, pull requests merged in 2020-06, with the labels that each got.

#3977 enable loading config.yml files from URL
  .pre-commit-config.yaml
  aiida/cmdline/commands/cmd_import.py
  aiida/cmdline/params/options/__init__.py
  aiida/cmdline/params/options/config.py
  aiida/cmdline/params/types/__init__.py
  aiida/cmdline/params/types/path.py
  aiida/common/extendeddicts.py
  docs/requirements_for_rtd.txt
  docs/source/nitpick-exceptions
  docs/source/reference/command_line.rst
  environment.yml
  requirements/requirements-py-3.5.txt
  requirements/requirements-py-3.6.txt
  requirements/requirements-py-3.7.txt
  requirements/requirements-py-3.8.txt
  setup.json
  tests/cmdline/commands/test_code.py
  tests/cmdline/commands/test_import.py
  tests/cmdline/params/types/test_path.py
Labels: pr/on-hold

#4147 Docs: Add release version pinning to install instructions
  docs/source/intro/get_started.rst
Labels: topic/dependencies

#4156 `WorkChain`: guarantee to maintain order of appended awaitables
  aiida/engine/processes/workchains/workchain.py
  docs/source/topics/workflows/usage.rst
Labels: pr/blocked

#4150 Increase the default for `runner.poll.interval` config option to 60
  aiida/manage/configuration/options.py
Labels: pr/on-hold

#4198 Update dependency requirement `kiwipy~=0.5.5`
  docs/requirements_for_rtd.txt
  environment.yml
  requirements/requirements-py-3.5.txt
  requirements/requirements-py-3.6.txt
  requirements/requirements-py-3.7.txt
  requirements/requirements-py-3.8.txt
  setup.json
Labels: dependencies, topic/dependencies

#4203 Docs: update ReadTheDocs configuration file
  .gitignore
  .pre-commit-config.yaml
  .readthedocs.yml
  aiida/sphinxext/tests/.gitignore
  docs/.gitignore
  docs/README.rst
  docs/requirements_for_rtd.txt
  docs/source/.gitignore
  docs/source/conf.py
  utils/dependency_management.py
Labels: pr/on-hold
