Repository aiidateam/aiida-core, pull requests merged in 2020-10, with the labels that each got.

#4412 REST API: list endpoints at base URL
  aiida/restapi/api.py
  aiida/restapi/resources.py
  docs/source/reference/rest_api.rst
  tests/restapi/test_routes.py
Labels: pr/ready-for-review

#4467 Docs: add info on export format to internals section
  docs/source/conf.py
  docs/source/import_export/main.rst
  docs/source/internals/data_storage.rst
  docs/source/internals/includes/data.json
  docs/source/internals/includes/metadata.json
  docs/source/internals/index.rst
  docs/source/redirects.txt
Labels: pr/next-to-merge

#4490 Docs: Remove `modifying_the_schema.rst`
  docs/source/developer_guide/core.rst
  docs/source/developer_guide/core/modifying_the_schema.rst
Labels: pr/next-to-merge

#4489 Docs: move list of public API to the "Reference" section
  docs/source/developer_guide/design/changes.rst
  docs/source/redirects.txt
  docs/source/reference/api/index.rst
  docs/source/reference/api/public.rst
  docs/source/reference/index.rst
  docs/source/working_with_aiida/deleting_nodes.rst
  docs/source/working_with_aiida/index.rst
Labels: pr/next-to-merge

#4488 Docs: update REST API wsgi scripts
  aiida/restapi/api.py
  aiida/restapi/run_api.py
  docs/source/howto/include/snippets/aiida-rest.conf
  docs/source/howto/include/snippets/myprofile-rest.wsgi
  docs/source/howto/share_data.rst
  docs/wsgi/__init__.py
  docs/wsgi/app1/__init__.py
  docs/wsgi/app1/config.py
  docs/wsgi/app1/rest.wsgi
  docs/wsgi/app2/__init__.py
  docs/wsgi/app2/config.py
  docs/wsgi/app2/rest.wsgi
  docs/wsgi/many.conf
  docs/wsgi/one.conf
  tests/restapi/test_routes.py
Labels: pr/next-to-merge

#4493 Docs: merge REST API query instructions
  docs/source/conf.py
  docs/source/howto/share_data.rst
  docs/source/redirects.txt
  docs/source/reference/rest_api.rst
  docs/source/restapi/index.rst
Labels: pr/next-to-merge

#4492 Docs: extend REST API
  docs/source/conf.py
  docs/source/developer_guide/core/extend_restapi.rst
  docs/source/howto/share_data.rst
  docs/source/internals/includes/snippets/api.py
  docs/source/internals/index.rst
  docs/source/internals/rest_api.rst
  docs/source/redirects.txt
Labels: pr/next-to-merge

#4508 Docs: Add `verdi process status` command to tutorial
  docs/source/intro/tutorial.rst
Labels: priority/nice-to-have, topic/documentation

#4393 verdi migrate --in-place between file systems
  aiida/cmdline/commands/cmd_export.py
Labels: pr/ready-for-review
