Repository aiidateam/aiida-core, pull requests merged in 2020-09, with the labels that each got.

#4343 CI: limit upper version of `setuptools<50` for Jenkins build
  .ci/Jenkinsfile
  pyproject.toml
  utils/dependency_management.py
Labels: pr/on-hold

#4364 Docs: Fix RabbitMQ configuration table
  docs/source/intro/installation.rst
Labels: topic/documentation

#3931 Implement `Scheduler.parse_output` for the `SlurmScheduler` plugin
  aiida/schedulers/plugins/slurm.py
  tests/schedulers/test_slurm.py
Labels: pr/ready-for-review

#4369 Ci/continue on errors with 2020 resolver
  .github/workflows/test-install.yml
Labels: topic/dependencies, topic/testing

#4378 Unpin numpy version from 1.17.X to allow the newest version (1.19)
  .circleci/config.yml
  .github/workflows/ci-code.yml
  .github/workflows/ci-style.yml
  .github/workflows/release.yml
  aiida/tools/data/array/kpoints/legacy.py
  environment.yml
  setup.json
Labels: dependencies, pr/ready-for-review, priority/important, topic/dependencies, topics/dependencies/constraint

#4370 `CalcJob`: improve logging in `parse_scheduler_output`
  aiida/engine/processes/calcjobs/calcjob.py
  tests/conftest.py
  tests/engine/processes/test_exit_code.py
  tests/engine/test_calc_job.py
Labels: priority/critical-blocking

#4380 Do not run `process_handler` when `exit_codes=[]`.
  aiida/engine/processes/workchains/utils.py
  tests/engine/processes/workchains/test_utils.py
Labels: pr/ready-for-review, priority/nice-to-have, requires discussion, topic/workflows

#4344 Prepare the code for the new repository implementation
  aiida/cmdline/commands/cmd_code.py
  aiida/cmdline/commands/cmd_node.py
  aiida/cmdline/utils/repository.py
  aiida/engine/daemon/execmanager.py
  aiida/manage/backup/backup_general.py
  aiida/manage/database/integrity/duplicate_uuid.py
  aiida/orm/nodes/data/code.py
  aiida/orm/nodes/data/singlefile.py
  aiida/orm/nodes/node.py
  aiida/orm/utils/_repository.py
  aiida/orm/utils/repository.py
  aiida/repository/__init__.py
  aiida/repository/common.py
  aiida/restapi/translator/nodes/node.py
  aiida/tools/importexport/dbexport/__init__.py
  aiida/tools/importexport/dbimport/backends/django/__init__.py
  aiida/tools/importexport/dbimport/backends/sqla/__init__.py
  tests/cmdline/commands/test_node.py
  tests/cmdline/utils/test_repository.py
  tests/orm/utils/test_repository.py
  tests/restapi/test_routes.py
  tests/tools/importexport/test_specific_import.py
Labels: pr/ready-for-review, priority/critical-blocking

#4328 Add 'extras' column to Group database class
  aiida/backends/djsite/db/migrations/0045_dbgroup_extras.py
  aiida/backends/djsite/db/migrations/__init__.py
  aiida/backends/djsite/db/models.py
  aiida/backends/sqlalchemy/migrations/versions/0edcdd5a30f0_add_extras_to_group.py
  aiida/backends/sqlalchemy/migrations/versions/0edcdd5a30f0_dbgroup_extras.py
  aiida/backends/sqlalchemy/models/group.py
  aiida/orm/groups.py
  aiida/orm/implementation/django/utils.py
  aiida/orm/implementation/sqlalchemy/utils.py
  aiida/orm/nodes/data/remote.py
  tests/backends/aiida_django/migrations/test_migrations_0045_dbgroup_extras.py
  tests/backends/aiida_sqlalchemy/test_migrations.py
  tests/orm/test_groups.py
Labels: pr/blocked

#4402 Release/1.4.1
  CHANGELOG.md
  aiida/__init__.py
  aiida/cmdline/params/options/__init__.py
  aiida/cmdline/params/options/commands/setup.py
  aiida/orm/nodes/node.py
  docs/source/intro/installation.rst
  docs/source/reference/command_line.rst
  environment.yml
  requirements/requirements-py-3.5.txt
  requirements/requirements-py-3.6.txt
  requirements/requirements-py-3.7.txt
  requirements/requirements-py-3.8.txt
  setup.json
  tests/orm/node/test_node.py
Labels: pr/on-hold
