Repository aiidateam/aiida-core, pull requests merged in 2020-04, with the labels that each got.

#3901 Use GitHub Actions services (for PostgreSQL and RabbitMQ)
  .github/workflows/ci.yml
  .github/workflows/test-install.yml
  .github/workflows/update-requirements.yml
Labels: priority/quality-of-life, topic/continuous-integration

#3918 Trigger test-install workflow for pull requests.
  .github/workflows/test-install.yml
Labels: topic/dependencies, topic/testing

#3948 Make the job submission script configurable through `CalcJob` options
  aiida/engine/daemon/execmanager.py
  aiida/engine/processes/calcjobs/calcjob.py
  aiida/engine/processes/calcjobs/tasks.py
Labels: priority/critical-blocking

#3958 add github action of transifex upload
  .ci/transifex_upload.sh
  .github/workflows/release.yml
Labels: topic/continuous-integration, topic/documentation

#3969 Fix bug in `verdi daemon restart --reset`
  aiida/cmdline/commands/cmd_daemon.py
  tests/cmdline/commands/test_daemon.py
Labels: pr/ready-for-review

#3957 Update update-dependency flow to resolve issue #3930
  .github/workflows/ci.yml
  .github/workflows/test-install.yml
  .github/workflows/update-requirements.yml
  requirements/README.md
  utils/dependency_management.py
Labels: pr/ready-for-review, topic/continuous-integration, topic/dependencies

#3976 Add codecov.yml codecov configuration file
  .github/workflows/tests.sh
  codecov.yml
  pytest.ini
Labels: pr/ready-for-review
