Repository aiidateam/aiida-core, pull requests merged in 2021-04, with the labels that each got.

#4851 Fix/issue 4850
  setup.json
  utils/dependency_management.py
Labels: dependencies, topic/dependencies, topics/dependencies/constraint

#4562 Docs: Add "How to extend workflows" section
  docs/source/howto/include/snippets/extend_workflows.py
  docs/source/howto/index.rst
  docs/source/howto/plugin_codes.rst
  docs/source/howto/run_workflows.rst
  docs/source/howto/workchains_restart.rst
  docs/source/howto/write_workflows.rst
  docs/source/intro/tutorial.rst
  docs/source/topics/processes/usage.rst
  docs/source/topics/workflows/index.rst
  docs/source/topics/workflows/usage.rst
Labels: requires discussion, topic/documentation

#4860 CI: install default `postgresql` instead of specific version
  .github/workflows/ci-code.yml
  .github/workflows/rabbitmq.yml
  .github/workflows/release.yml
  .github/workflows/test-install.yml
Labels: topic/continuous-integration

#4862 Revert "CI: Notify slack on failure of the test-install workflow.
  .github/workflows/test-install.yml
Labels: topic/dependencies

#4761 `verdi calcjob gotocomputer`: Add proxy command
  aiida/transports/plugins/ssh.py
  tests/transports/test_ssh.py
Labels: topic/transports, topic/verdi, type/bug

#4889 `Manager`: check if repository container has been initialised
  aiida/manage/configuration/profile.py
  aiida/manage/manager.py
Labels: priority/critical-blocking, topic/repository
