Repository aiidateam/aiida-core, pull requests merged in 2021-08, with the labels that each got.

#4855 Dependencies: update `sqlalchemy` dependency requirements
  aiida/backends/sqlalchemy/models/__init__.py
  aiida/backends/sqlalchemy/models/comment.py
  aiida/backends/sqlalchemy/models/log.py
  environment.yml
  requirements/requirements-py-3.7.txt
  requirements/requirements-py-3.8.txt
  requirements/requirements-py-3.9.txt
  setup.json
Labels: dependencies, topic/dependencies

#5043 Dependencies: Bump pytz to version 2021.1
  environment.yml
  requirements/requirements-py-3.7.txt
  requirements/requirements-py-3.8.txt
  requirements/requirements-py-3.9.txt
  setup.json
Labels: dependencies, topic/dependencies, topics/dependencies/constraint

#5046 Dependencies: Bump jinja2 to version 3.0
  environment.yml
  requirements/requirements-py-3.7.txt
  requirements/requirements-py-3.8.txt
  requirements/requirements-py-3.9.txt
  setup.json
Labels: topic/dependencies, dependencies, topics/dependencies/constraint

#4707 Allow setting `rerunnable` from `metadata['options']`
  aiida/engine/processes/calcjobs/calcjob.py
  aiida/schedulers/plugins/direct.py
  aiida/schedulers/plugins/sge.py
  docs/source/topics/calculations/usage.rst
  tests/engine/test_calc_job.py
  tests/schedulers/test_direct.py
  tests/schedulers/test_lsf.py
  tests/schedulers/test_pbspro.py
  tests/schedulers/test_sge.py
  tests/schedulers/test_slurm.py
  tests/schedulers/test_torque.py
Labels: topic/calc-jobs
