Repository aiidateam/aiida-core, pull requests merged in 2021-02, with the labels that each got.

#4715 Dependencies: Require `ipython~=7.20`
  environment.yml
  requirements/requirements-py-3.7.txt
  requirements/requirements-py-3.8.txt
  requirements/requirements-py-3.9.txt
  setup.json
Labels: topic/dependencies

#4725 🔧 MAINTAIN: drop setuptools upper pinning
  pyproject.toml
  utils/dependency_management.py
Labels: topic/dependencies

#4724 Upgrading dependency of sqlalchemy-utils
  environment.yml
  requirements/requirements-py-3.7.txt
  requirements/requirements-py-3.8.txt
  requirements/requirements-py-3.9.txt
  setup.json
Labels: topic/dependencies

#4728 `verdi group remove-nodes`: Add warning when nodes are not in `Group`
  aiida/cmdline/commands/cmd_group.py
  tests/cmdline/commands/test_group.py
Labels: topic/verdi

#4747 Skip test 'TestVerdiProcessDaemon::test_pause_play_kill'.
  tests/cmdline/commands/test_process.py
Labels: topic/testing
